
package nl.vijfhart.ws;

import javax.jws.WebService;
import javax.xml.ws.BindingType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 */
@WebService(portName = "HelloWorldImplPort", serviceName = "/ws/hello/HelloWorldWebService", targetNamespace = "http://ws.vijfhart.nl/", wsdlLocation = "http://localhost:7003/VijfhartWebapp/ws/hello/HelloWorldService?wsdl", endpointInterface = "nl.vijfhart.ws.HelloWorld")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class JwshelloHelloWorldWebService_HelloWorldImplPortImpl
        implements HelloWorld {


    public JwshelloHelloWorldWebService_HelloWorldImplPortImpl() {
    }

    /**
     * @param arg0
     * @return returns java.lang.String
     */
    public String getHelloWorldAsString(String arg0) {
        //replace with your impl here
        return null;
    }

}
